language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules

after_success: gulp build

before_deploy: git config --global user.name "Travis CI" && git config --global user.email "travis@travis-ci.org"
deploy: 
  skip_cleanup: true
  provider: pages
  github_token: $GH_TOKEN
  local_dir: _book
  on: 
    branch: master
