language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules

after_success:
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - gulp build
  - gulp publish

branches:
  only: master
