language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules

install:
  - npm install -g gitbook-cli
  - npm install

deploy:
  provider: script
  script: npm run deploy
  on:
    branch: master

branches:
  except:
    - /.+-experimental/